"""Formal message definitions for module-level contracts."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping

from .topics import (
    ANNOTATION_CORRECTED,
    ANNOTATION_STORED,
    EMBEDDING_CREATED,
    IMAGE_SUBMITTED,
    INFERENCE_COMPLETED,
    QUERY_COMPLETED,
    QUERY_SUBMITTED,
)


class MessageDefinitionError(ValueError):
    """Raised when topic payload does not match the defined contract."""


@dataclass(frozen=True)
class MessageDefinition:
    topic: str
    publisher: str
    subscribers: tuple[str, ...]
    required_payload_fields: tuple[str, ...]
    description: str


MESSAGE_DEFINITIONS: dict[str, MessageDefinition] = {
    IMAGE_SUBMITTED: MessageDefinition(
        topic=IMAGE_SUBMITTED,
        publisher="UploadService/CLIService",
        subscribers=("InferenceService",),
        required_payload_fields=("image_id", "path", "source", "timestamp"),
        description="Ingress image event generated by user upload.",
    ),
    INFERENCE_COMPLETED: MessageDefinition(
        topic=INFERENCE_COMPLETED,
        publisher="InferenceService",
        subscribers=("DocumentDBService",),
        required_payload_fields=("image_id", "path", "source", "model_version", "objects"),
        description="Simulated detection and annotation output.",
    ),
    ANNOTATION_STORED: MessageDefinition(
        topic=ANNOTATION_STORED,
        publisher="DocumentDBService",
        subscribers=("EmbeddingService",),
        required_payload_fields=("image_id", "object_count", "review_status"),
        description="Notification that canonical annotation document is persisted.",
    ),
    EMBEDDING_CREATED: MessageDefinition(
        topic=EMBEDDING_CREATED,
        publisher="EmbeddingService",
        subscribers=("VectorIndexService",),
        required_payload_fields=("image_id", "embeddings"),
        description="Embedding vectors produced for image and detected objects.",
    ),
    ANNOTATION_CORRECTED: MessageDefinition(
        topic=ANNOTATION_CORRECTED,
        publisher="CLIService/Reviewer",
        subscribers=("DocumentDBService",),
        required_payload_fields=("image_id", "notes"),
        description="Manual annotation correction event from reviewer action.",
    ),
    QUERY_SUBMITTED: MessageDefinition(
        topic=QUERY_SUBMITTED,
        publisher="CLIService",
        subscribers=("QueryService",),
        required_payload_fields=("query_id", "query_type", "top_k"),
        description="Retrieval request for either text query or image reference.",
    ),
    QUERY_COMPLETED: MessageDefinition(
        topic=QUERY_COMPLETED,
        publisher="QueryService",
        subscribers=("CLIService",),
        required_payload_fields=("query_id", "query_type", "query", "top_k", "results"),
        description="Retrieval response from the query worker.",
    ),
}


def get_message_definition(topic: str) -> MessageDefinition:
    definition = MESSAGE_DEFINITIONS.get(topic)
    if definition is None:
        raise MessageDefinitionError(f"unknown topic: {topic}")
    return definition


def validate_payload(topic: str, payload: Mapping[str, Any]) -> None:
    definition = get_message_definition(topic)
    missing_fields = [key for key in definition.required_payload_fields if key not in payload]
    if missing_fields:
        missing = ", ".join(missing_fields)
        raise MessageDefinitionError(f"topic {topic} missing payload fields: {missing}")
